dist: trusty
sudo: required
language: go

go:
  - 1.8.x

go_import_path: github.com/percona/percona-toolkit

before_install:
  - perl -v

script:
  - perl Makefile.PL
  - make
  - make test

  - prove -vwr t/*

  - make -C percona-toolkit/src/go

  - sudo make install
