dist: trusty
sudo: required
language: go

go:
  - 1.8.x

go_import_path: github.com/percona/percona-toolkit

install:
  - pwd
  - perl -v

  - curl https://glide.sh/get | sh
  - glide install --strip-vendor

script:
  - perl Makefile.PL
  - make
  - make test

  - prove -vwr t/*

  - make -C src/go

  - sudo make install
